export const PS_ICON_PATHS = {
  'home-compass': 'navigation/home-compass.svg',
  'adventures-book': 'navigation/adventures-book.svg',
  'play-pokeball': 'navigation/play-pokeball.svg',
  'collection-chest': 'navigation/collection-chest.svg',
  'more-backpack': 'navigation/more-backpack.svg',
  'notes-scroll': 'navigation/notes-scroll.svg',
  'search-magnifier': 'navigation/search-magnifier.svg',
  'settings-gear': 'navigation/settings-gear.svg',
  'notifications-bell': 'navigation/notifications-bell.svg',
  menu: 'navigation/menu.svg',

  'goal-target': 'session/goal-target.svg',
  'characters-group': 'session/characters-group.svg',
  'timeline-scroll': 'session/timeline-scroll.svg',
  'ai-crystal': 'session/ai-crystal.svg',
  'quick-event-dice': 'session/quick-event-dice.svg',
  'exploration-footprints': 'session/exploration-footprints.svg',
  'battle-swords': 'session/battle-swords.svg',
  campfire: 'session/campfire.svg',
  'mystery-book': 'session/mystery-book.svg',
  'reward-gift': 'session/reward-gift.svg',
  'print-queue': 'session/print-queue.svg',
  'add-note': 'session/add-note.svg',
  'new-npc': 'session/new-npc.svg',
  'scene-change': 'session/scene-change.svg',
  'wait-hourglass': 'session/wait-hourglass.svg',

  'pokedex-book': 'collection/pokedex-book.svg',
  'pokemon-sticker': 'collection/pokemon-sticker.svg',
  'items-potion': 'collection/items-potion.svg',
  'clothing-shirt': 'collection/clothing-shirt.svg',
  'badge-medal': 'collection/badge-medal.svg',
  'npc-card': 'collection/npc-card.svg',
  'location-card': 'collection/location-card.svg',
  'quest-card': 'collection/quest-card.svg',
  'achievement-star': 'collection/achievement-star.svg',
  'treasure-chest': 'collection/treasure-chest.svg',
  'reward-box': 'collection/reward-box.svg',
  printer: 'collection/printer.svg',
  'queue-box': 'collection/queue-box.svg',
  'printed-check': 'collection/printed-check.svg',
  reprint: 'collection/reprint.svg',

  'character-profile': 'world/character-profile.svg',
  'npc-dialogue': 'world/npc-dialogue.svg',
  'location-pin': 'world/location-pin.svg',
  'world-map': 'world/world-map.svg',
  'world-fact': 'world/world-fact.svg',
  'document-scroll': 'world/document-scroll.svg',
  'tag-label': 'world/tag-label.svg',
  'filter-funnel': 'world/filter-funnel.svg',
  'secret-keyhole': 'world/secret-keyhole.svg',
  'twist-mask': 'world/twist-mask.svg',
  'faction-shield': 'world/faction-shield.svg',
  'environment-forest': 'world/environment-forest.svg',
  'weather-sun-cloud': 'world/weather-sun-cloud.svg',
  'encounter-claw': 'world/encounter-claw.svg',
  'scene-landscape': 'world/scene-landscape.svg',

  'success-check': 'status/success-check.svg',
  'warning-triangle': 'status/warning-triangle.svg',
  'error-cross': 'status/error-cross.svg',
  'info-orb': 'status/info-orb.svg',
  'locked-padlock': 'status/locked-padlock.svg',
  'unlocked-padlock': 'status/unlocked-padlock.svg',
  'pending-hourglass': 'status/pending-hourglass.svg',
  'sync-arrows': 'status/sync-arrows.svg',
  'offline-cloud': 'status/offline-cloud.svg',
  'saved-scroll': 'status/saved-scroll.svg',
  'favorite-star': 'status/favorite-star.svg',
  'archive-box': 'status/archive-box.svg',
  'delete-bin': 'status/delete-bin.svg',
  'edit-quill': 'status/edit-quill.svg',
  'add-spark': 'status/add-spark.svg',
} as const;

export type PsIconName = keyof typeof PS_ICON_PATHS;
